version: '3'
services:
  postgres:
    restart: always
    image: postgres:12
    env_file:
      - database.env
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
   restart: always
   build: .
   ports:
     - 8000:8000
   command: bash -c "alembic upgrade head && gunicorn -w 4 -b :8000 app:app"
   
   volumes: 
     - .:/app/scr
   network_mode: host  

   depends_on:
     - postgres
 
      
